# Topics
# camera_topic: "/zed2i/zed_node/left/image_rect_color"
# camera_info: "/zed2i/zed_node/left/camera_info"
camera_topic: "/flir_lwir/image_thresholded"
camera_info: "/flir_lwir/camera_info"
lidar_topic: "/velodyne_points"

# Dynamic rqt_reconfigure default bounds
feature_extraction:
  x_min: -10.0
  x_max: 10.0
  y_min: -8.0
  y_max: 8.0
  z_min: -5.0
  z_max: 5.0
  
# Properties of chessboard calibration target

# Small Board (for the Black Body)
# chessboard:
#   pattern_size:
#     height: 6
#     width: 7
#   square_length: 22
#   board_dimension:
#     width: 209
#     height: 239
#   translation_error:
#     x: 0
#     y: 25.5 # 15mm, 66mm

# Big Board
chessboard:
  pattern_size:
    height: 5
    width: 3  
  square_length: 94
  board_dimension:
    width: 598
    height: 1055
  translation_error:
    x: 0 
    y: 3.5 #145, 152